### ISSUE TITLE
Experience section should have urls for individual items.

### ISSUE THREAD

**Issue by masasin** [masasin/resume#3]
The education section already has this feature, with:

```
urls:
    school:
    major:
    affiliation:
```

The experience section can use:

```
urls:
    employer:
    department:
```

This is useful for labs or large companies.
